#!/usr/bin/env bash

nitrogen --restore
nohup gnome-screensaver &>/dev/null &
nohup pulseaudio &>/dev/null &
nohup pasystray &>/dev/null &
nohup nm-applet &>/dev/null &
#sudo sh -c 'systemctl stop ntpd && ntpdate $(awk "/^server/ {print \$2}" /etc/ntp.conf) && systemctl start ntpd'
