#!/usr/bin/env bash

nitrogen --restore
nohup /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &>/dev/null &
nohup pulseaudio &>/dev/null &
nohup pasystray &>/dev/null &
nohup pidgin &>/dev/null &
nohup nm-applet &>/dev/null &
