#!/usr/bin/python

import os

def replace_chars(path='.', old=' ', new='_', folders=False):
	for root, dirs, files in os.walk(os.path.abspath(path)):

		files = [f for f in files if old in f]

		if files:
			new_files = [os.path.join(root, f.replace(old,new)) for f in files]
			files = [os.path.join(root, f) for f in files]
			[os.rename(o, n) for o, n in zip(files, new_files)]

		old_dirs = [d for d in dirs if old in d]

		if old_dirs and folders:
			new_dirs = [os.path.join(root, d.replace(old, new)) for d in old_dirs]
			old_dirs = [os.path.join(root, d) for d in old_dirs]
			[os.rename(o,n) for o, n in zip(old_dirs, new_dirs)]
		
			tdirs = [os.path.join(root, d) for d in os.listdir(root)]
			tdirs = [d for d in tdirs if os.path.isdir(d)]

			for i in range(len(dirs)):
				dirs.pop()
			dirs.extend(tdirs)


if __name__ == '__main__':
	import sys

	if sys.argv[1] == '-f':
		folders = True
		args = sys.argv[2:]
	else:
		folders = False
		args = sys.argv[1:]

	replace_chars(*args, folders=folders)
